# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_placement_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 488)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 3, 1, 1, 1)
        self.btn_open = QtWidgets.QPushButton(Form)
        self.btn_open.setObjectName("btn_open")
        self.gridLayout.addWidget(self.btn_open, 0, 0, 1, 1)
        self.lbl_item = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_item.sizePolicy().hasHeightForWidth())
        self.lbl_item.setSizePolicy(sizePolicy)
        self.lbl_item.setObjectName("lbl_item")
        self.gridLayout.addWidget(self.lbl_item, 1, 0, 1, 1)
        self.cmb_items = QtWidgets.QComboBox(Form)
        self.cmb_items.setObjectName("cmb_items")
        self.gridLayout.addWidget(self.cmb_items, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 468))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_items = QtWidgets.QVBoxLayout()
        self.layout_items.setObjectName("layout_items")
        self.verticalLayout_2.addLayout(self.layout_items)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scroll_area)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Order placement"))
        self.btn_add.setText(_translate("Form", "Add"))
        self.btn_open.setText(_translate("Form", "Open"))
        self.lbl_item.setText(_translate("Form", "Item"))
        self.btn_save.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
