# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'engine_item_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(689, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cmb_gas_capacity = QtWidgets.QComboBox(Form)
        self.cmb_gas_capacity.setObjectName("cmb_gas_capacity")
        self.gridLayout.addWidget(self.cmb_gas_capacity, 2, 0, 1, 1)
        self.radio_btn_diesel = QtWidgets.QRadioButton(Form)
        self.radio_btn_diesel.setObjectName("radio_btn_diesel")
        self.gridLayout.addWidget(self.radio_btn_diesel, 0, 1, 1, 1)
        self.lbl_diesel_capacity = QtWidgets.QLabel(Form)
        self.lbl_diesel_capacity.setObjectName("lbl_diesel_capacity")
        self.gridLayout.addWidget(self.lbl_diesel_capacity, 1, 1, 1, 1)
        self.lbl_gas_capacity = QtWidgets.QLabel(Form)
        self.lbl_gas_capacity.setObjectName("lbl_gas_capacity")
        self.gridLayout.addWidget(self.lbl_gas_capacity, 1, 0, 1, 1)
        self.cmb_diesel_capacity = QtWidgets.QComboBox(Form)
        self.cmb_diesel_capacity.setObjectName("cmb_diesel_capacity")
        self.gridLayout.addWidget(self.cmb_diesel_capacity, 2, 1, 1, 1)
        self.radio_btn_gas = QtWidgets.QRadioButton(Form)
        self.radio_btn_gas.setObjectName("radio_btn_gas")
        self.gridLayout.addWidget(self.radio_btn_gas, 0, 0, 1, 1)
        self.lbl_quantity = QtWidgets.QLabel(Form)
        self.lbl_quantity.setObjectName("lbl_quantity")
        self.gridLayout.addWidget(self.lbl_quantity, 3, 0, 1, 1)
        self.spb_quantity = QtWidgets.QSpinBox(Form)
        self.spb_quantity.setObjectName("spb_quantity")
        self.gridLayout.addWidget(self.spb_quantity, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radio_btn_diesel.setText(_translate("Form", "Diesel"))
        self.lbl_diesel_capacity.setText(_translate("Form", "Capacity"))
        self.lbl_gas_capacity.setText(_translate("Form", "Capacity"))
        self.radio_btn_gas.setText(_translate("Form", "Gas"))
        self.lbl_quantity.setText(_translate("Form", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
