# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'door_item_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(343, 123)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cmb_hor_type = QtWidgets.QComboBox(Form)
        self.cmb_hor_type.setObjectName("cmb_hor_type")
        self.gridLayout.addWidget(self.cmb_hor_type, 1, 1, 1, 1)
        self.lbl_type = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_type.sizePolicy().hasHeightForWidth())
        self.lbl_type.setSizePolicy(sizePolicy)
        self.lbl_type.setObjectName("lbl_type")
        self.gridLayout.addWidget(self.lbl_type, 0, 0, 1, 1)
        self.lbl_quantity = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_quantity.sizePolicy().hasHeightForWidth())
        self.lbl_quantity.setSizePolicy(sizePolicy)
        self.lbl_quantity.setObjectName("lbl_quantity")
        self.gridLayout.addWidget(self.lbl_quantity, 2, 0, 1, 1)
        self.cmb_vert_type = QtWidgets.QComboBox(Form)
        self.cmb_vert_type.setObjectName("cmb_vert_type")
        self.gridLayout.addWidget(self.cmb_vert_type, 1, 0, 1, 1)
        self.spb_quantity = QtWidgets.QSpinBox(Form)
        self.spb_quantity.setObjectName("spb_quantity")
        self.gridLayout.addWidget(self.spb_quantity, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_type.setText(_translate("Form", "Type"))
        self.lbl_quantity.setText(_translate("Form", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
